version: '3'

services:
  db:
    image: mysql:8
    ports:
      - "3306:3306"
    restart: always
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
    volumes:
      - ./mysql/initialize_sql:/docker-entrypoint-initdb.d