name: Go Test
on: push

jobs:
  go-test:
    name: Go Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.0.0
      - name: MySQL Container Start
        run: docker compose up -d
      - name: Run Test
        run: go test -v ./...